spring:
  boot:
    admin:
      client:
        url: http://localhost:8081
        username: admin
        password: admin@123
management:
  endpoints:
    web:
      exposure:
        include: loggers, health, info
  endpoint:
    loggers:
      enabled: true
    health:
      show-details: always