spring:
  boot:
    admin:
      client:
        url: http://localhost:8081
        username: ben
        password: benspassword
        instance:
          service-host-type: IP
        period: 300000ms
        auto-deregistration: true
management:
  endpoints:
    web:
      exposure:
        include: loggers, health, info
  endpoint:
    loggers:
      enabled: true
    health:
      show-details: always